
networks:
  b2b_network:
    driver: bridge
  traefik-net:
    external: true

services:
  frontend:
    build: .
    image: techchaide/crm-resiflex-frontend:1.0
    container_name: crm-resiflex_frontend_prod
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_BASE_PATH=/CRMContactosResiflex
      - HOSTNAME=0.0.0.0
    volumes:
      - "/fotomenu:/app/fotomenu"
      - "/fotosevo/activos_it:/app/activos_it"
    networks:
      - b2b_network
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.crm-resiflex-frontend-prod.rule=Host(`apps.chaide.com`) && PathPrefix(`/CRMContactosResiflex`)"
      - "traefik.http.routers.crm-resiflex-frontend-prod.entrypoints=websecure"
      - "traefik.http.routers.crm-resiflex-frontend-prod.priority=100"
      - "traefik.http.routers.crm-resiflex-frontend-prod.tls=true"
      - "traefik.http.services.crm-resiflex-frontend-prod.loadbalancer.server.port=3000"